# Generated by Django 2.2.12 on 2022-04-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Marks',
            fields=[
                ('roll_no', models.CharField(db_column='Roll_No', max_length=25, primary_key=True, serialize=False)),
                ('sem_id', models.CharField(db_column='Sem_Id', max_length=10)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=2, null=True)),
                ('pass_fail', models.CharField(blank=True, db_column='Pass_Fail', max_length=25, null=True)),
                ('credits', models.CharField(blank=True, db_column='Credits', max_length=25, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, db_column='total_Marks', null=True)),
            ],
            options={
                'db_table': 'Student_Marks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=25, null=True)),
                ('branch_name', models.CharField(blank=True, db_column='branch_Name', max_length=25, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=255, null=True)),
                ('degree_type', models.CharField(blank=True, db_column='Degree_Type', max_length=25, null=True)),
                ('roll_no', models.CharField(db_column='Roll_No', max_length=25, primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, db_column='Father_name', max_length=25, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Student_Profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student_Subjects',
            fields=[
                ('sem_id', models.CharField(db_column='Sem_Id', max_length=255, primary_key=True, serialize=False)),
                ('sub_name1', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_name2', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_name3', models.CharField(blank=True, max_length=20, null=True)),
                ('roll_no', models.CharField(db_column='Roll_No', max_length=25)),
            ],
            options={
                'db_table': 'Student_Subjects',
                'managed': True,
            },
        ),
    ]
