# Generated by Django 2.2.12 on 2022-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20220414_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Marks',
            fields=[
                ('ind', models.CharField(db_column='Ind_No', max_length=25, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(db_column='Roll_No', max_length=25)),
                ('sem_id', models.CharField(db_column='Sem_Id', max_length=10)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=2, null=True)),
                ('pass_fail', models.CharField(blank=True, db_column='Pass_Fail', max_length=25, null=True)),
                ('credits', models.CharField(blank=True, db_column='Credits', max_length=25, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, db_column='total_Marks', null=True)),
            ],
            options={
                'db_table': 'Student_Marks',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Student_Profile1',
            new_name='Student_Profile',
        ),
        migrations.RenameModel(
            old_name='Student_Subjects1',
            new_name='Student_Subjects',
        ),
        migrations.DeleteModel(
            name='Student_Marks1',
        ),
        migrations.AlterModelTable(
            name='student_profile',
            table='Student_Profile',
        ),
        migrations.AlterModelTable(
            name='student_subjects',
            table='Student_Subjects',
        ),
    ]
