# Generated by Django 2.2.4 on 2022-06-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_name', models.CharField(blank=True, max_length=20, null=True)),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('animal_age', models.CharField(blank=True, max_length=3, null=True)),
                ('animal_symptom', models.CharField(blank=True, max_length=50, null=True)),
                ('animal_amount', models.IntegerField()),
                ('animal_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('doctor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('payment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('details_status', models.CharField(blank=True, max_length=100, null=True)),
                ('details_amount', models.IntegerField(blank=True, null=True)),
                ('details_prescription', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
