# Generated by Django 4.0.5 on 2022-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
