# Generated by Django 4.0.5 on 2022-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_alter_animal_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
