# Generated by Django 4.0.5 on 2022-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_alter_animal_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='animal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
