# Generated by Django 4.0.5 on 2022-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_first_name_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
